# Numpy

In [1]:
import numpy as np

## The basics

In [4]:
a = np.array([1, 2, 3])
print (a)

[1 2 3]


In [8]:
b = np.array([[1, 2, 3],[6, 5, 0]])
print (b)

[[1 2 3]
 [6 5 0]]


In [9]:
# get dim

In [10]:
a.ndim

1

In [11]:
b.ndim

2

In [12]:
b.shape

(2, 3)

In [13]:
# get type

In [15]:
a.dtype

dtype('int64')

In [16]:
a.itemsize

8

In [17]:
a.size

3

In [18]:
a.nbytes

24

## Accessing/ Changing  specific elements

In [24]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [21]:
a[1, 1]

9

In [22]:
#specicic rows

In [23]:
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [26]:
#apecific column
a[:, 2]

array([ 3, 10])

In [27]:
#stepwise
a[0, 1:6:2]

array([2, 4, 6])

In [28]:
#Changing elements

In [29]:
a[1,5] = 22

In [30]:
print (a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 22 14]]


In [31]:
#changing a series of numbers

In [33]:
a[0, 1:6] = 3
print (a)

[[ 1  3  3  3  3  3  7]
 [ 8  9 10 11 12 22 14]]


In [34]:
a[0, 1:6:2] = [2, 4, 6]

In [35]:
print (a)

[[ 1  2  3  4  3  6  7]
 [ 8  9 10 11 12 22 14]]


# 3d array

In [37]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [40]:
# Get specific element (work outside in)
b[0,1,1]

4

In [42]:
# Get specific element (work outside in) so say if I wanted 3, 4
b[0, 1, :]

array([3, 4])

In [43]:
# replace 
b[:,1,:] = [[9,9],[8,8]]

In [44]:
print (b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


## Initializing Different Types of Arrays

In [47]:
np.zeros((2,3,3), dtype = 'int32')

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=int32)

In [49]:
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [50]:
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [52]:
np.full(a.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [53]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.93345369, 0.28555386],
       [0.50472967, 0.89152208],
       [0.73348589, 0.32047381],
       [0.2796352 , 0.67731214]])

In [54]:
np.random.randomsample(a.shape)

AttributeError: module 'numpy.random' has no attribute 'randomsample'

In [61]:
# Random Integer values
np.random.randint(4,22, size=(3,3))

array([[ 5, 10, 10],
       [ 7, 20,  8],
       [17, 11, 19]])

In [64]:
# The identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [65]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [70]:
output = np.ones((5,5))
# print(output)

z = np.zeros((3,3))
z[1,1] = 9
# print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [71]:
# be careful with copy

In [72]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


In [73]:
print (b)

[100   2   3]


## Math

In [74]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [75]:
a + 2

array([3, 4, 5, 6])

In [77]:
a - 2

array([-1,  0,  1,  2])

In [78]:
# Take the sin
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [79]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

### Linear Algebra

In [81]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b) # matrix multiplier in np is matmul

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [82]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [83]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

### Statistics

In [89]:
stats = np.array([[1,2,3],[4,5,6]])
print (stats)

[[1 2 3]
 [4 5 6]]


In [86]:
np.min(stats)

1

In [87]:
np.max(stats)

6

In [88]:
np.max(stats, axis = 0)

array([4, 5, 6])

In [90]:
np.max(stats, axis = 1)

array([3, 6])

### Reorganizing Arrays

In [97]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print (before.shape)
print(before)

after = before.reshape((4,2))
print(after)

# You can think of this as ### after = before.reshape((4,2)) --> Axis 1 (Columns =2,) axis 0 (rows = 4)

(2, 4)
[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### Miscellaneous
##### Load Data from File

In [ ]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)