### NLP Sentiment Analysis Exercise

In [1]:
# import numpy 
import numpy as np 

# import pandas
import pandas as pd 

# import regex
import re

# import nltk
import nltk 

In [6]:
# load data
data = "/Users/patrickokwir/Desktop/Lighthouse-data-notes/Unit_9/Day_1/Tweets.csv"
df = pd.read_csv(data)

**Task:** Print the top 5 rows.

In [7]:
df.head()

tweet_id airline_sentiment  airline_sentiment_confidence  \
0  570306133677760513           neutral                        1.0000   
1  570301130888122368          positive                        0.3486   
2  570301083672813571           neutral                        0.6837   
3  570301031407624196          negative                        1.0000   
4  570300817074462722          negative                        1.0000   

  negativereason  negativereason_confidence         airline  \
0            NaN                        NaN  Virgin America   
1            NaN                     0.0000  Virgin America   
2            NaN                        NaN  Virgin America   
3     Bad Flight                     0.7033  Virgin America   
4     Can't Tell                     1.0000  Virgin America   

  airline_sentiment_gold        name negativereason_gold  retweet_count  \
0                    NaN     cairdin                 NaN              0   
1                    NaN    jnardino                 NaN              0   
2                    NaN  yvonnalynn                 NaN              0   
3                    NaN    jnardino                 NaN              0   
4                    NaN    jnardino                 NaN              0   

                                                text tweet_coord  \
0                @VirginAmerica What @dhepburn said.         NaN   
1  @VirginAmerica plus you've added commercials t...         NaN   
2  @VirginAmerica I didn't today... Must mean I n...         NaN   
3  @VirginAmerica it's really aggressive to blast...         NaN   
4  @VirginAmerica and it's a really big bad thing...         NaN   

               tweet_created tweet_location               user_timezone  
0  2015-02-24 11:35:52 -0800            NaN  Eastern Time (US & Canada)  
1  2015-02-24 11:15:59 -0800            NaN  Pacific Time (US & Canada)  
2  2015-02-24 11:15:48 -0800      Lets Play  Central Time (US & Canada)  
3  2015-02-24 11:15:36 -0800            NaN  Pacific Time (US & Canada)  
4  2015-02-24 11:14:45 -0800            NaN  Pacific Time (US & Canada)

**Task:** Use the `'text'` column to create an array with the name `'features'`.



In [9]:
# use the text column to create an array of features
features = df['text'].values

**Task:** Use `'airline_sentiment'` column to create an array with the name `'labels'`.

In [10]:
labels = df['airline_sentiment'].values

**Task:** Clean the text data in the `'features'` array.

    - Remove all the special characters.
    - Remove all single characters.
    - Remove single characters from the start.
    - Substituting multiple spaces with single space.
    - Converting all text to lowercase.

In [12]:
processed_features = []

for sentence in range(0, len(features)):
    # Remove all the special characters
    sentence_text = re.sub(r"[^a-zA-Z0-9]", " ", features[sentence])

    # Remove all single characters
    sentence_text = re.sub(r"\s+[a-zA-Z]\s+", " ", sentence_text)

    # Remove single characters from the start
    sentence_text = re.sub(r"^\s+[a-zA-Z]\s+", " ", sentence_text)
    
    # Substituting multiple spaces with single space
    sentence_text = re.sub(r"\s+", " ", sentence_text)
    
    # Converting to Lowercase
    sentence_text = sentence_text.lower()

    # Removing stop words
    #sentence_text = " ".join([word for word in sentence_text.split() if word not in (stopwords.words('english'))])

    processed_features.append(sentence_text)

    

**Task:** Import stopwords from nltk.

In [13]:
#import stopwords from nltk
from nltk.corpus import stopwords

**Task:** Import TfidfVectorizer from sklearn.

In [14]:
# import TfidfVectorizer from sklearn
from sklearn.feature_extraction.text import TfidfVectorizer

**Task:** Instatiate TfidfVectorizer with following parameters:

    - max_features = 2500
    - min_df = 7
    - max_df = 0.8
    - stop_words = stopwords.words('english')
    
    


In [15]:
# instantiate TfidfVectorizer
tfidf = TfidfVectorizer(max_features=2500, min_df=7, max_df=0.8, stop_words=stopwords.words('english'))


**Bonus:** How would you determine optimal paraemeters for TfidfVectorizer? Discuss with your peers and/or mentors. Write down your answer below.

**Task:** Transform features with vectorizer. 

In [16]:
# transform features with vectorizer
processed_features = tfidf.fit_transform(processed_features).toarray()

**Task:** Import train_test_split from sklearn and split the data.

In [17]:
# import train_test_split from sklearn
from sklearn.model_selection import train_test_split

X = processed_features
y = labels

# split data into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

**Task:** Import any classifier of your choice from sklearn (e.g. Random Forest, LogReg, Naive Bayes).

In [20]:
# import naive bayes
from sklearn import naive_bayes
from sklearn.metrics import roc_auc_score



**Task:** Fit your classifier to data.

In [21]:
# instantiate classifier
clf = naive_bayes.MultinomialNB()

**Task:** Predict X_test.

In [22]:
clf.fit(X_train, y_train)

MultinomialNB()

**Task:** Import confusion matrix and accuracy_score.

In [23]:
# import confusion matrix and accuracy score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

**Task:** Print confusion matrix.

In [24]:
# print confusion matrix
print(confusion_matrix(y_test, clf.predict(X_test)))

[[1832   45   12]
 [ 375  188   17]
 [ 204   37  218]]


**Task:** Print accaccuracy_score.

In [26]:
# print accuracy score
print(accuracy_score(y_test, clf.predict(X_test)))

0.764344262295082
