# Basic Operations with Matrices
---

In [2]:
import numpy as np

Creating Vectors and Matrices with Numpy


We will start by creating a vector. This is a numpy.ndarray (n-dimensional array) with one dimension

In [2]:
x = np.array([1, 2, 3, 4, 5])
x

array([1, 2, 3, 4, 5])

In [15]:
#create a 3X2 matrix (2D array) with nested brackets 
A = np.array([[1, 2], [3, 4], [5, 6]])

In [4]:
#check the shape of the array
type(A)

numpy.ndarray

The shape of an array tells us the number of values for each dimension. For a 2-dimensional array, it will give us the number of rows and the number of columns. 

Let’s find the shape of the previous 2-dimensional matrix A. Since A is a numpy.ndarray (it was created with the `array()` function), we can access its shape attribute with:

In [5]:
A.shape

(3, 2)

In [6]:
x.shape

(5,)

In [7]:
len(x)

5

#### Transposition of a Matrix

We can access the `transpose()` method of a numpy.ndarray object by:

In [16]:
A_T = A.T

In [13]:
A_T = A.transpose()

In [18]:
A_T.shape

(2, 3)

### Matrix addition

In [19]:
B = np.array([[2, 5], [7, 4], [4, 3]])

In [ ]:
# Add the matrix A to B and save the result in a matrix C
C = A + B

### Matrix Multiplication

The standard way to multiply matrices is not to multiply each element of one matrix with each element of another one (called the element-wise product), but to calculate the sum of the products between the rows and the columns. `A matrix product is also called a dot product.`

The number of columns of the first matrix must be equal to the number of rows of the second one. If the dimensions of the first matrix are (m×n), the second matrix needs to be of shape (n×x). The resulting matrix will have the shape (m×x).

To compute a matrix product we can use the Numpy function `dot().`

In [20]:
A = np.array([[1, 2], [3, 4], [5, 6]])

In [21]:
B = np.array([[2], [4]])

In [22]:
# Perform matrix multiplication between A and B. Because the matrix A has 2 columns and the matrix B has 2 rows, we can multiply them and store the result in a matrix C
C = np.dot(A, B)

In [24]:
C.shape

(3, 1)

### Identity Matrices

An identity matrix **In** is a special square (nxn) matrix which has 1s on the main diagonal and 0s everywhere else.

An identity matrix can be created with the Numpy function `eye():`

In [27]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
# multiply matrix A and the identity matrix and save the result in matrix B
IA = I.dot(A)
IA

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [30]:
# OR 
IA = np.dot(I, A)
IA

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

### Determinant

To compute a determinant of a matrix using Numpy, we have to use the `linalg module`. The `numpy.linalg` module specializes in linear algebra with matrices and vectors.

In [3]:
# Define a new matrix M with the shape (2x2):
M = np.array([[1, 2], [3, 4]])
M

array([[1, 2],
       [3, 4]])

In [24]:
M.shape

(2, 2)

In [4]:
# Compute the determinant of the matrix M:
det_M = np.linalg.det(M)

In [6]:
det_M

-2.0000000000000004

`Determinants can be computed only from square matrices.`

### Inverse Matrices

The inverse matrix of A with shape `(nxn)` is denoted as `A-1.` It is a matrix that when multiplied by A, resultsin an identity matrix. `(AA-1 = In)`. This means that if we apply a linear transformation to the matrix with A, it is possible to go back with A-1. This provides a way to cancel the transformation.

For this example, we will use the Numpy function linalg.inv() to calculate the inverse of A. Let’s start by creating A with the shape (3x3):

In [20]:
# creater a matrix A with a shape of 3x3:
A = np.array([[3, 0, 2], [2, 0, -2], [0, 1, 1]])
A

array([[ 3,  0,  2],
       [ 2,  0, -2],
       [ 0,  1,  1]])

In [21]:
# Calculate the inverse of the matrix A:
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.2,  0.2,  0. ],
       [-0.2,  0.3,  1. ],
       [ 0.2, -0.3, -0. ]])

In [19]:
# calculate the iverse of A_inv and save it to a I:
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.2,  0.2,  0. ],
       [-0.2,  0.3,  1. ],
       [ 0.2, -0.3, -0. ]])

In [22]:
#check if A_inv is really the inverse of A:
I = A_inv.dot(A)

In [23]:
I

array([[ 1.00000000e+00,  0.00000000e+00, -1.11022302e-16],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])